import Head from 'next/head'
import IntroHeader from "../components/introHeader";
import RecentPosts from "../components/recentPosts";
import FeaturedWork from "../components/featuredWork";

import {getAllPosts} from "../lib/api";

export async function getStaticProps() {
  const posts = getAllPosts();

  return {
    props: {
      posts,
    },
  };
}

export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <IntroHeader />
        <RecentPosts posts={posts} />
        <FeaturedWork />
    </div>
  )
}
