import Head from 'next/head'
import Work from "../components/work";

export default function WorkPage() {
    return (
        <div>
            <Head>
                <title>NextJS Work</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className='px-6'>
                <div className='max-w-4xl mx-auto'>
                    <h1 className='text-3xl font-bold mb-6 p-4'>Work</h1>
                    <Work />
                    <Work />
                    <Work />
                    <Work />
                </div>
            </section>
        </div>
    )
}
